export const ErrorCode = {
  // Common
  BAD_REQUEST: 'NEST-400',
  UNAUTHORIZED: 'NEST-401',
  FORBIDDEN: 'NEST-403',
  NOT_FOUND: 'NEST-404',
  INTERNAL_SERVER_ERROR: 'NEST-500',

  // User exception (Default: NEST-01xx)
  USER_ALREADY_EXIST: 'NEST-0101',
  WRONG_PASSWORD: 'NEST-0102',
  INVALID_REFRESH_TOKEN: 'NEST-0103',
  USER_NOT_FOUND: 'NEST-0104',
  USER_HAS_ALREADY_CHANGED_PASSWORD: 'NEST-0105',
  NEW_PASSWORD_SAME_AS_CURRENT_PASSWORD: 'NEST-0106',
};
